services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile

    # Mount the whole project into /app
    volumes:
      - .:/app
      # Keep node_modules inside a Docker volume (Linux), not on host
      - node_modules:/app/node_modules

    restart: always

    ports:
      - "3000:3000"

    networks:
      - my_network

volumes:
  node_modules:

networks:
  my_network:
    external: true
