import type { Metadata } from "next";
import { Inter,Kaushan_Script } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer/Footer";



const geistMono = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const kaushan = Kaushan_Script({
  subsets: ["latin"],
  weight: "400", // Kaushan Script only has 400
  variable: "--font-kaushan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${kaushan.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
